{ ... }:

{
  homebrew = {
    enable = true;

    onActivation = {
      autoUpdate = true;
      # 初回は "check" で「未管理パッケージのリスト表示のみ」。動作確認後 "uninstall" に切り替えて
      # 自動同期を有効化する (`nix/homebrew.nix` から外したパッケージが自動 uninstall される)。
      cleanup = "check";
      upgrade = false;
    };

    taps = [
      "adoptopenjdk/openjdk"
      "homebrew/cask-fonts"
      "daipeihust/tap"
      "microsoft/apm"
    ];

    brews = [
      "1password-cli"
      "FairwindsOps/tap/pluto"
      "age"
      "ansible"
      "argoproj/tap/argocd"
      "asdf"
      "automake"
      "azure-cli"
      "basictex"
      "bash-completion"
      "bat"
      "chezmoi"
      "chromium"
      "cloc"
      "cloudflared"
      "cmake"
      "codex"
      "coreutils"
      "cue"
      "curl"
      "direnv"
      "ffmpeg"
      "fujiwara/tap/tfstate-lookup"
      "gdb"
      "gh"
      "git"
      "gnu-sed"
      "googleworkspace-cli"
      "graphviz"
      "helm"
      "htop"
      "im-select"
      "imagemagick"
      "jq"
      "k1LoW/tap/tbls"
      "kayac/tap/ecspresso"
      "krew"
      "kubectx"
      "kustomize"
      "libmagic"
      "libpq"
      "llvm"
      "markdownlint-cli"
      "marp-cli"
      "mas"
      "mecab"
      "microsoft/apm/apm"
      "mutagen-io/mutagen/mutagen-compose"
      "mysql"
      "neovim"
      "pandoc"
      "parallel"
      "peco"
      "pipx"
      "pstree"
      "qemu"
      "readline"
      "redis"
      "repomix"
      "ripgrep"
      "ruby-build"
      "stern"
      "terminal-notifier"
      "the_silver_searcher"
      "tig"
      "tmux"
      "tmuxinator"
      "tree"
      "vim"
      "watch"
      "wget"
      "yarn"
      "yq"
      "yukiarrr/tap/ecsk"
      "zlib"
      "zsh"
      "zsh-autosuggestions"
      "zsh-completions"
      "zsh-syntax-highlighting"
    ];

    casks = [
      "adoptopenjdk11"
      "avidemux"
      "brave-browser"
      "claude-code"
      "clipy"
      "cursor"
      "dash"
      "docker"
      "firefox"
      "font-jetbrains-mono"
      "font-source-code-pro"
      "font-source-han-code-jp"
      "freefilesync"
      "gcloud"
      "ghostty"
      "google-chrome"
      "google-japanese-ime"
      "handbrake"
      "intellij-idea"
      "kindle"
      "obsidian"
      "raycast"
      "react-native-debugger"
      "session-manager-plugin"
      "slack"
      "temurin"
      "the-unarchiver"
      "visual-studio-code"
      "vlc"
      "zoom"
    ];
  };
}
